import { StyleSheet } from 'react-native';
import { Theme } from '@/core/theme/theme';
import { moderateScale } from '@/shared/utils/responsive';

export const styles = (theme: Theme, insets: any, isDarkMode: boolean) => StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: theme.colors.background,
    },
    headerGradient: {
        paddingTop: insets.top + 10,
        paddingBottom: 15,
        borderBottomLeftRadius: 35,
        borderBottomRightRadius: 35,
        overflow: 'hidden',
    },
    headerContent: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 20,
    },
    headerTitle: {
        fontSize: moderateScale(20),
        fontWeight: '900',
        color: '#FFFFFF',
        letterSpacing: -0.5,
    },
    backButton: {
        width: 44,
        height: 44,
        borderRadius: 15,
        backgroundColor: 'rgba(255, 255, 255, 0.15)',
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: 'rgba(255, 255, 255, 0.2)',
    },
    headerRight: {
        width: 44,
        height: 44,
        borderRadius: 15,
        backgroundColor: 'rgba(255, 255, 255, 0.15)',
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: 'rgba(255, 255, 255, 0.2)',
    },
    sectionHeader: {
        paddingHorizontal: 25,
        paddingVertical: 15,
        backgroundColor: theme.colors.background,
    },
    sectionTitle: {
        fontSize: 13,
        fontWeight: '800',
        color: theme.colors.textSecondary,
        textTransform: 'uppercase',
        letterSpacing: 1.5,
    },
    listContent: {
        paddingHorizontal: 20,
        paddingBottom: insets.bottom + 100,
    },
    notificationCard: {
        flexDirection: 'row',
        padding: 18,
        borderRadius: 24,
        backgroundColor: isDarkMode ? 'rgba(255, 255, 255, 0.03)' : '#FFFFFF',
        marginBottom: 12,
        borderWidth: 1,
        borderColor: isDarkMode ? 'rgba(255, 255, 255, 0.08)' : '#F1F5F9',
    },
    unreadCard: {
        backgroundColor: isDarkMode ? 'rgba(59, 130, 246, 0.05)' : '#F8FAFF',
        borderColor: isDarkMode ? 'rgba(59, 130, 246, 0.2)' : '#E0E7FF',
    },
    cardContent: {
        flex: 1,
    },
    cardHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'flex-start',
        marginBottom: 4,
    },
    notifTitle: {
        fontSize: 15,
        fontWeight: '800',
        color: theme.colors.text,
        flex: 1,
        marginRight: 10,
        letterSpacing: -0.3,
    },
    unreadDot: {
        width: 8,
        height: 8,
        borderRadius: 4,
        backgroundColor: '#3B82F6',
        marginTop: 6,
    },
    notifDesc: {
        fontSize: 13,
        lineHeight: 18,
        color: theme.colors.textSecondary,
        marginBottom: 10,
        opacity: 0.8,
    },
    cardFooter: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    timeContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 4,
    },
    notifTime: {
        fontSize: 11,
        fontWeight: '700',
        color: theme.colors.textSecondary,
        opacity: 0.5,
    },
    emptyState: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
        paddingTop: 100,
        paddingHorizontal: 40,
    },
    emptyImageContainer: {
        width: 120,
        height: 120,
        borderRadius: 60,
        backgroundColor: isDarkMode ? 'rgba(59, 130, 246, 0.1)' : '#F0F7FF',
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 25,
    },
    emptyTitle: {
        fontSize: 20,
        fontWeight: '900',
        color: theme.colors.text,
        textAlign: 'center',
        marginBottom: 10,
    },
    emptySubtitle: {
        fontSize: 14,
        color: theme.colors.textSecondary,
        textAlign: 'center',
        lineHeight: 22,
        opacity: 0.7,
    },
});
