import { StyleSheet } from 'react-native';
import { Theme } from '@/core/theme/theme';
import { moderateScale, verticalScale } from '@/shared/utils/responsive';

export const styles = (theme: Theme, isDarkMode: boolean) => StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: theme.colors.background,
    },
    header: {
        height: verticalScale(110),
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 20,
    },
    headerTitle: {
        fontSize: moderateScale(19),
        fontWeight: '900',
        color: '#FFFFFF',
        letterSpacing: 0.5,
    },
    backButton: {
        width: 42,
        height: 42,
        borderRadius: 14,
        backgroundColor: 'rgba(255, 255, 255, 0.12)',
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: 'rgba(255, 255, 255, 0.1)',
    },
    headerRight: {
        width: 42,
        height: 42,
        justifyContent: 'center',
        alignItems: 'center',
    },
    scrollContent: {
        paddingHorizontal: 16,
        paddingBottom: 60,
    },
    summarySection: {
        marginTop: 15,
        marginBottom: 24,
    },
    summaryCard: {
        flexDirection: 'row',
        backgroundColor: theme.colors.card,
        borderRadius: 22,
        paddingVertical: 20,
        paddingHorizontal: 14,
        borderWidth: 1.5,
        borderColor: isDarkMode ? 'rgba(255, 255, 255, 0.08)' : '#D1D5DB',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 10 },
        shadowOpacity: isDarkMode ? 0.3 : 0.08,
        shadowRadius: 20,
        elevation: 6,
    },
    summaryItem: {
        flex: 1,
        alignItems: 'center',
    },
    summaryDivider: {
        width: 1.5,
        height: '60%',
        backgroundColor: isDarkMode ? 'rgba(255, 255, 255, 0.1)' : '#E2E8F0',
        alignSelf: 'center',
    },
    summaryLabel: {
        fontSize: moderateScale(9),
        fontWeight: '900',
        color: isDarkMode ? theme.colors.textSecondary : '#64748B',
        letterSpacing: 0.8,
        marginBottom: 6,
        textAlign: 'center',
    },
    summaryValue: {
        fontSize: moderateScale(19),
        fontWeight: '900',
        color: isDarkMode ? '#FFFFFF' : '#182958',
    },
    semesterCard: {
        backgroundColor: theme.colors.card,
        borderRadius: 24,
        marginBottom: 24,
        overflow: 'hidden',
        borderWidth: 1.5,
        borderColor: isDarkMode ? 'rgba(255, 255, 255, 0.05)' : '#D1D5DB',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 6 },
        shadowOpacity: isDarkMode ? 0.2 : 0.04,
        shadowRadius: 15,
        elevation: 4,
    },
    semesterHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: 18,
        borderBottomWidth: 1,
        borderBottomColor: isDarkMode ? 'rgba(255, 255, 255, 0.03)' : '#E2E8F0',
    },
    semesterTitleWrapper: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    semesterBlueIndicator: {
        width: 4,
        height: 32,
        backgroundColor: '#3B82F6',
        borderRadius: 2,
        marginRight: 12,
    },
    semesterTitleText: {
        fontSize: moderateScale(15),
        fontWeight: '900',
        color: isDarkMode ? '#FFFFFF' : '#1E293B',
        marginBottom: 2,
    },
    semesterSubtitleText: {
        fontSize: moderateScale(11),
        fontWeight: '700',
        color: '#94A3B8',
        textTransform: 'uppercase',
        letterSpacing: 0.6,
    },
    semesterGpaBadge: {
        alignItems: 'center',
        backgroundColor: isDarkMode ? 'rgba(255, 255, 255, 0.03)' : '#FFFFFF',
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 14,
        borderWidth: 1,
        borderColor: isDarkMode ? 'rgba(255, 255, 255, 0.05)' : '#E2E8F0',
    },
    semesterGpaLabel: {
        fontSize: moderateScale(9),
        fontWeight: '800',
        color: '#64748B',
        marginBottom: 1,
    },
    semesterGpaValue: {
        fontSize: moderateScale(15),
        fontWeight: '900',
        color: isDarkMode ? theme.colors.primary : '#182958',
    },
    tableHeader: {
        flexDirection: 'row',
        paddingHorizontal: 18,
        paddingVertical: 12,
        backgroundColor: isDarkMode ? 'rgba(255, 255, 255, 0.015)' : '#F8FAFC',
        borderBottomWidth: 1,
        borderBottomColor: isDarkMode ? 'rgba(255, 255, 255, 0.03)' : '#F1F5F9',
    },
    tableHeaderStats: {
        flex: 1.8,
        flexDirection: 'row',
        alignItems: 'center',
    },
    columnLabel: {
        fontSize: moderateScale(9),
        fontWeight: '900',
        color: '#94A3B8',
        letterSpacing: 0.4,
    },
    statCol: {
        flex: 1,
        textAlign: 'center',
    },
    gradeCol: {
        flex: 1.2,
        textAlign: 'center',
    },
    courseList: {
        backgroundColor: 'transparent',
    },
    courseRow: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 14,
        paddingHorizontal: 18,
        borderBottomWidth: 1,
        borderBottomColor: isDarkMode ? 'rgba(255, 255, 255, 0.03)' : '#E2E8F0', 
    },
    courseName: {
        fontSize: moderateScale(13),
        fontWeight: '800',
        color: isDarkMode ? theme.colors.text : '#1E293B',
        marginBottom: 2,
    },
    courseCodeWrapper: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 4,
    },
    courseCode: {
        fontSize: moderateScale(10),
        fontWeight: '700',
        color: '#94A3B8',
        letterSpacing: 0.4,
    },
    courseValue: {
        fontSize: moderateScale(13),
        fontWeight: '700',
        color: isDarkMode ? theme.colors.textSecondary : '#475569',
    },
    gradeBadge: {
        width: 38,
        height: 28,
        borderRadius: 8,
        alignItems: 'center',
        justifyContent: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 1,
    },
    gradeText: {
        fontSize: moderateScale(12),
        fontWeight: '900',
        color: '#FFFFFF',
    },
    semesterFooter: {
        paddingHorizontal: 18,
        paddingVertical: 14,
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        backgroundColor: isDarkMode ? 'rgba(255, 255, 255, 0.01)' : '#FDFEFF',
        borderTopWidth: 1,
        borderTopColor: isDarkMode ? 'rgba(255, 255, 255, 0.03)' : '#F1F5F9',
    },
    footerLeft: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
    },
    footerInfoText: {
        fontSize: moderateScale(11),
        fontWeight: '600',
        color: '#94A3B8',
    },
    footerStats: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
    },
    footerSummaryText: {
        fontSize: moderateScale(10),
        fontWeight: '800',
        color: isDarkMode ? theme.colors.textSecondary : '#64748B',
    },
    footerSummaryValue: {
        backgroundColor: isDarkMode ? 'rgba(255, 255, 255, 0.05)' : '#F1F5F9',
        paddingHorizontal: 8,
        paddingVertical: 3,
        borderRadius: 6,
        fontSize: moderateScale(11),
        fontWeight: '900',
        color: isDarkMode ? theme.colors.primary : '#182958',
    },
});
